/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "maxWords": number;
        "pairs": Array<any>;
    }
    interface OneWord {
        "isSelected": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLOneWordElement extends Components.OneWord, HTMLStencilElement {
    }
    var HTMLOneWordElement: {
        prototype: HTMLOneWordElement;
        new (): HTMLOneWordElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "one-word": HTMLOneWordElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "maxWords"?: number;
        "pairs"?: Array<any>;
    }
    interface OneWord {
        "isSelected"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "one-word": OneWord;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "one-word": LocalJSX.OneWord & JSXBase.HTMLAttributes<HTMLOneWordElement>;
        }
    }
}
